import { LegalPageShell, LegalSection } from "@/components/LegalPageShell";
import { getCompanySettings } from "@/lib/company-settings";
import { getCurrentTenant } from "@/lib/tenant-server";
import IndiaPrivacy from "@/components/legal/IndiaPrivacy";

export const metadata = { title: "Privacy Notice — FasTrack Shop" };

const TOC = [
  { id: "scope", label: "1. What this notice covers" },
  { id: "information-we-collect", label: "2. Information we collect" },
  { id: "how-we-use", label: "3. How we use your information" },
  { id: "location", label: "4. Location information" },
  { id: "cookies", label: "5. Cookies & similar technologies" },
  { id: "notifications", label: "6. Push notifications" },
  { id: "content-you-share", label: "7. Information you choose to share" },
  { id: "sellers-partners", label: "8. Sellers & delivery partners" },
  { id: "security", label: "9. How we secure your information" },
  { id: "retention", label: "10. Data retention" },
  { id: "your-rights", label: "11. Your rights" },
  { id: "children", label: "12. Children's privacy" },
  { id: "changes", label: "13. Changes to this notice" },
  { id: "contact", label: "14. How to contact us" },
];

export default async function PrivacyPage() {
  const company = await getCompanySettings();
  // The legal text follows the market being used: India has its own terms and privacy notice.
  if ((await getCurrentTenant())?.country_code === "IN") return <IndiaPrivacy company={company} />;

  return (
    <LegalPageShell
      title="Privacy Notice"
      effectiveDate="September 30, 2026"
      intro={`This Privacy Notice describes how ${company.trading_name} ("FasTrack", "we", "us") collects, uses, and protects your personal information when you use the FasTrack Shop website and app, in line with the Kingdom of Saudi Arabia's Personal Data Protection Law (PDPL).`}
      toc={TOC}
    >
      <LegalSection id="scope" heading="1. What this notice covers">
        <p>
          This notice applies to personal information we collect through FasTrack, including when you browse
          products, create an account, place an order, contact support, or interact with sellers and delivery
          partners through the platform.
        </p>
      </LegalSection>

      <LegalSection id="information-we-collect" heading="2. Information we collect">
        <p>We collect information you provide directly and information generated by your use of FasTrack:</p>
        <ul className="list-disc space-y-1 ps-5">
          <li>
            <span className="font-medium text-neutral-800">Account information:</span> your name, phone number,
            email address, and password.
          </li>
          <li>
            <span className="font-medium text-neutral-800">Order & delivery information:</span> delivery addresses,
            building/unit details, order history, and order notes.
          </li>
          <li>
            <span className="font-medium text-neutral-800">Location information:</span> the coordinates of your
            delivery addresses and, if you allow it, your device&apos;s live location to help place pins accurately
            and route riders.
          </li>
          <li>
            <span className="font-medium text-neutral-800">Payment-related information:</span> for Cash on Delivery
            orders, we record order totals and payment status; we do not process or store card numbers.
          </li>
          <li>
            <span className="font-medium text-neutral-800">Content you submit:</span> product reviews, ratings for
            sellers and delivery partners, and support/chat messages related to your orders.
          </li>
          <li>
            <span className="font-medium text-neutral-800">Device & usage information:</span> IP address, browser
            or app version, and push notification subscription details, collected automatically when you use
            FasTrack.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="how-we-use" heading="3. How we use your information">
        <ul className="list-disc space-y-1 ps-5">
          <li>To create and manage your account and process your orders.</li>
          <li>To route your order to the nearest warehouse or seller and assign a delivery partner.</li>
          <li>To send order confirmations, delivery updates, and tax invoices by email, SMS, or push notification.</li>
          <li>To respond to support requests and resolve disputes, refunds, or delivery issues.</li>
          <li>To detect and prevent fraud, abuse, and violations of our Conditions of Use.</li>
          <li>To improve FasTrack&apos;s catalog, delivery coverage, and overall service quality.</li>
          <li>To meet our legal and tax obligations, including ZATCA e-invoicing requirements.</li>
        </ul>
      </LegalSection>

      <LegalSection id="location" heading="4. Location information">
        <p>
          We use the coordinates of your saved addresses to determine which warehouse or seller can deliver to you,
          calculate delivery zones, and give riders accurate pickup and drop-off points. You can manage or remove
          saved addresses at any time from your account.
        </p>
      </LegalSection>

      <LegalSection id="cookies" heading="5. Cookies & similar technologies">
        <p>
          We use essential cookies and similar local storage technologies to keep you signed in, remember your
          cart and delivery address, and understand basic usage of FasTrack. We do not use these technologies to
          sell your information to third parties.
        </p>
      </LegalSection>

      <LegalSection id="notifications" heading="6. Push notifications">
        <p>
          If you opt in, we send push notifications for order status updates, delivery arrival, and important
          account or order-related alerts. You can disable push notifications at any time through your browser or
          device settings.
        </p>
      </LegalSection>

      <LegalSection id="content-you-share" heading="7. Information you choose to share">
        <p>
          Reviews, ratings, and any names or photos you attach to them may be visible to other users and to the
          seller or delivery partner being rated. Do not include sensitive personal information in content you
          submit publicly.
        </p>
      </LegalSection>

      <LegalSection id="sellers-partners" heading="8. Sellers & delivery partners">
        <p>
          To fulfill your order, we share the information necessary to do so — such as your delivery address,
          phone number, and order contents — with the seller fulfilling the order and the delivery partner
          assigned to it. Sellers and delivery partners are independent parties who must handle your information
          responsibly and only for the purpose of completing your order.
        </p>
        <p>
          We do not sell your personal information to third parties for marketing purposes.
        </p>
      </LegalSection>

      <LegalSection id="security" heading="9. How we secure your information">
        <p>
          We apply access controls, encryption in transit, and role-based data access (for example, restricting a
          seller&apos;s visibility to only their own orders and products) to protect your information. No method of
          transmission or storage is completely secure, but we work to protect your information using
          industry-standard practices.
        </p>
      </LegalSection>

      <LegalSection id="retention" heading="10. Data retention">
        <p>
          We retain account and order information for as long as your account is active and afterward as needed to
          comply with our legal, tax, and accounting obligations (including ZATCA invoicing records), resolve
          disputes, and enforce our agreements.
        </p>
      </LegalSection>

      <LegalSection id="your-rights" heading="11. Your rights">
        <p>Subject to applicable law, you may have the right to:</p>
        <ul className="list-disc space-y-1 ps-5">
          <li>Access the personal information we hold about you.</li>
          <li>Request correction of inaccurate or incomplete information.</li>
          <li>Request deletion of your account and associated personal information, subject to our legal retention obligations.</li>
          <li>Withdraw consent to optional communications, such as promotional messages or push notifications.</li>
        </ul>
        <p>
          You can exercise most of these rights directly from your account settings, or by contacting us using the
          details in Section 14.
        </p>
      </LegalSection>

      <LegalSection id="children" heading="12. Children's privacy">
        <p>
          FasTrack is not directed at children under 18, and we do not knowingly collect personal information from
          them. If you believe a child has provided us with personal information, please contact us so we can
          remove it.
        </p>
      </LegalSection>

      <LegalSection id="changes" heading="13. Changes to this notice">
        <p>
          We may update this Privacy Notice from time to time to reflect changes to our practices or for legal
          reasons. Changes take effect once posted on this page, with the &quot;Effective&quot; date updated
          accordingly.
        </p>
      </LegalSection>

      <LegalSection id="contact" heading="14. How to contact us">
        <p>
          For any questions about this Privacy Notice or to exercise your data rights, contact {company.trading_name}
          {company.email ? ` at ${company.email}` : ""}
          {company.phone ? ` or by phone at ${company.phone}` : ""}.
          {company.address_line || company.city
            ? ` Our registered address: ${[company.address_line, company.city].filter(Boolean).join(", ")}.`
            : ""}
        </p>
      </LegalSection>
    </LegalPageShell>
  );
}
